# Generated by Django 3.1.4 on 2021-02-24 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.CharField(max_length=500)),
                ('rate', models.IntegerField(choices=[('1', 'Hate it'), ('2', 'Disliked it'), ('3', 'It was ok'), ('4', 'like it'), ('5', 'Love it')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='home.account')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='home.account')),
            ],
        ),
        migrations.CreateModel(
            name='Hire_me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disciption', models.CharField(max_length=500)),
                ('job_titel', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_1', to='home.account')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_1', to='home.account')),
            ],
        ),
        migrations.CreateModel(
            name='Annoce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disciption', models.CharField(max_length=500)),
                ('job_titel', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_2', to='home.account')),
            ],
        ),
    ]
