# Generated by Django 3.1.4 on 2021-02-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Available',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='job',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
