# Generated by Django 3.1.4 on 2021-02-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210227_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Available',
            field=models.CharField(choices=[('Not Available', 'Not Available'), ('Available', 'Available'), ('Available form now', 'Available form now')], max_length=70, null=True),
        ),
    ]
