# Generated by Django 3.1.4 on 2021-02-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_account_acc_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Acc_pic',
            field=models.ImageField(blank=True, default='image.jfif', null=True, upload_to=''),
        ),
    ]
