# Generated by Django 3.1.4 on 2021-03-03 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210302_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hire_me',
            name='job_titel',
        ),
    ]
